"""initial_schema

Revision ID: d978bdb46a6a
Revises: 
Create Date: 2026-08-23 13:14:27.187773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd978bdb46a6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('referral_id', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('resident_ref', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('requested_action', sa.String(length=150), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('processing_state', sa.String(length=50), nullable=False),
    sa.Column('policy_decision', sa.String(length=50), nullable=True),
    sa.Column('workflow_disposition', sa.String(length=50), nullable=False),
    sa.Column('has_under_18', sa.Boolean(), nullable=True),
    sa.Column('is_resumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_index(op.f('ix_referrals_referral_id'), 'referrals', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referrals_resident_ref'), 'referrals', ['resident_ref'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.String(length=50), nullable=True),
    sa.Column('requested_action', sa.String(length=150), nullable=False),
    sa.Column('applicable_section', sa.String(length=100), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('supervisor_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_referral_id'), 'audit_logs', ['referral_id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('applicable_section', sa.String(length=100), nullable=False),
    sa.Column('rule_title', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('triage_permitted', sa.Boolean(), nullable=False),
    sa.Column('human_action_required', sa.String(length=250), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('resident_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.String(length=50), nullable=True),
    sa.Column('resident_ref', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('benefit_code', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('award_monthly', sa.Float(), nullable=False),
    sa.Column('household_raw', sa.JSON(), nullable=True),
    sa.Column('events_raw', sa.JSON(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('triage_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.String(length=50), nullable=True),
    sa.Column('summary_of_situation', sa.Text(), nullable=False),
    sa.Column('recommended_next_steps', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('drafted_by_llm', sa.Boolean(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_notes')
    op.drop_table('resident_snapshots')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_audit_logs_referral_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_referrals_resident_ref'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
